Amit Anil Jadhav
Personal Profile
Email: amitjadhavv02@gmail.com

Address: Max Planck Strasse 32, 91058 Erlangen, Germany

Phone: +491631993906

LinkedIn: https://www.linkedin.com/in/amit-jadhav24a0261

Experience
GSTech - Adspyder
Data Science Intern

April 2021 - September 2021

Data pre-processing on ads using Python and also Java.
Managing Kafka data pipelines.
Managing MongoDB and ElasticsearchDB Databases.
Played a major role in the projects Major Update where we processed millions of raw unstructured data into MongoDB and ElastichSearchDB using Kafka data pipelines.
Skills
Programming
Python (Advanced)
SQL (Advanced)
Java (Intermediate)
C Programming (Advanced)
HTML/ CSS (Intermediate)
PHP (Basic)
Software & Libraries
Pandas
Scikit learn
Matplotlib
Scipy
TensorFlow
Regular Expression
Selenium
Beautiful Soup
Power BI
Education
Masters in Data Science from Friedrich-Alexander University, Erlangen, Germany.
Bachelor of Engineering in Computer Science from The Oxford College of Engineering, Bangalore. V.T.U 2017 – 2021
Extra Curricular
BEST Erlangen e.V.
Vice President of Human Resources

July 2022- present

Organized Tech Events, competitions and technological Courses.
Projects
Gym Management System - Nov 2019
Developed a web application to manage Gym Client Data using HTML and CSS for Frontend and PHP, SQL for database on Xampp server
Computer Graphics Sheepish Game - April 2020
Developed a Computer Graphics Sheepish Game, Using OpenGL Libraries and C programming.
Sales Price Prediction on Housing dataset - July 2020
Built a XGBoost ML model to predict the sales price of houses with scikit learn and pandas libraries in Python.
Second-Hand Book Selling Website - December 2020
Developed a web Application for buying and selling second-hand books using PHP, CSS and Html
Road Traffic Sign Detection System Using CNN- June 2021
Implemented real-time IOT model for Road traffic sign detection using computer vision and Deep Learning technology using Tensorflow, OpenCV, Pandas and RaspberryPi in addition Developed an Android Application for Real-time UI with Voice and Visual alert System.
CERTIFICATIONS
Applied Data Science with Python Specialization.
Completed the Specialization from Coursera
Containing 5 Courses - October 2020
Introduction to Data Science in Python.
Applied Plotting, Charting & Data Representation in Python.
Applied Machine Learning in Python.
Applied Text Mining in Python.
Applied Social Network Analysis in Python.
Introduction to TensorFlow for Artificial Intelligence Machine Learning, and Deep Learning - October 2020
Convolutional Neural Networks in TensorFlow - November 2020
Natural Language Processing in TensorFlow - December 2021
